version: "3.7"

services: 
  app:
    container_name: tmp_app
    build: .
    env_file: 
      - auth.env
    volumes:
      - .:/usr/src/themoviepredictor
    networks:
      - database_net  
    command: tail -f /dev/null
    depends_on:
      - database
  database:
    container_name: tmp_database
    image: mysql:latest
    env_file:
      - auth.env
    networks:
      - database_net
    volumes: 
      - database_data:/var/lib/mysql
    command: --default_authentication_plugin=mysql_native_password
  
  adminer:
    container_name: tmp_adminer
    image: dehy/adminer
    ports: 
      - 8080:80
    networks: 
      - database_net

networks:
  database_net:
    name: tmp_network
    driver: bridge

volumes:
  database_data:
    name: tmp_volume